//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WGSTask.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContactDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContactDataEntities object using the connection string found in the 'ContactDataEntities' section of the application configuration file.
        /// </summary>
        public ContactDataEntities() : base("name=ContactDataEntities", "ContactDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContactDataEntities object.
        /// </summary>
        public ContactDataEntities(string connectionString) : base(connectionString, "ContactDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContactDataEntities object.
        /// </summary>
        public ContactDataEntities(EntityConnection connection) : base(connection, "ContactDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContactSet> ContactSets
        {
            get
            {
                if ((_ContactSets == null))
                {
                    _ContactSets = base.CreateObjectSet<ContactSet>("ContactSets");
                }
                return _ContactSets;
            }
        }
        private ObjectSet<ContactSet> _ContactSets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContactSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContactSets(ContactSet contactSet)
        {
            base.AddObject("ContactSets", contactSet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContactDataModel", Name="ContactSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContactSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContactSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="noHP">Initial value of the NoHP property.</param>
        public static ContactSet CreateContactSet(global::System.Int32 id, global::System.String name, global::System.String noHP)
        {
            ContactSet contactSet = new ContactSet();
            contactSet.Id = id;
            contactSet.Name = name;
            contactSet.NoHP = noHP;
            return contactSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoHP
        {
            get
            {
                return _NoHP;
            }
            set
            {
                OnNoHPChanging(value);
                ReportPropertyChanging("NoHP");
                _NoHP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoHP");
                OnNoHPChanged();
            }
        }
        private global::System.String _NoHP;
        partial void OnNoHPChanging(global::System.String value);
        partial void OnNoHPChanged();

        #endregion
    
    }

    #endregion
    
}
