//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGSTask.ContactReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactReference.IServiceAuthor")]
    public interface IServiceAuthor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthor/DoWork", ReplyAction="http://tempuri.org/IServiceAuthor/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAuthor/ReturnAuthor", ReplyAction="http://tempuri.org/IServiceAuthor/ReturnAuthorResponse")]
        System.Data.DataSet ReturnAuthor();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAuthorChannel : WGSTask.ContactReference.IServiceAuthor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAuthorClient : System.ServiceModel.ClientBase<WGSTask.ContactReference.IServiceAuthor>, WGSTask.ContactReference.IServiceAuthor {
        
        public ServiceAuthorClient() {
        }
        
        public ServiceAuthorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAuthorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAuthorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataSet ReturnAuthor() {
            return base.Channel.ReturnAuthor();
        }
    }
}
